// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ-eJRyJPHMUT0Z17V62iFAb5KengiS6k',
    appId: '1:471790702809:web:417f1b1e888f759720eec8',
    messagingSenderId: '471790702809',
    projectId: 'loopybot-97081',
    authDomain: 'loopybot-97081.firebaseapp.com',
    storageBucket: 'loopybot-97081.firebasestorage.app',
    measurementId: 'G-B1DEN16CQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChc5IcWQcJY7lJLocW8eFWXXrFZTJ56fI',
    appId: '1:471790702809:android:d67fc24751ead8ce20eec8',
    messagingSenderId: '471790702809',
    projectId: 'loopybot-97081',
    storageBucket: 'loopybot-97081.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5VoRJ7HnofVNLVExwMgfVkdNKv7Cgcio',
    appId: '1:471790702809:ios:524728d80bc1768920eec8',
    messagingSenderId: '471790702809',
    projectId: 'loopybot-97081',
    storageBucket: 'loopybot-97081.firebasestorage.app',
    iosClientId: '471790702809-j351mvdq215l2bdcitnkashd4mevvcre.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5VoRJ7HnofVNLVExwMgfVkdNKv7Cgcio',
    appId: '1:471790702809:ios:524728d80bc1768920eec8',
    messagingSenderId: '471790702809',
    projectId: 'loopybot-97081',
    storageBucket: 'loopybot-97081.firebasestorage.app',
    iosClientId: '471790702809-j351mvdq215l2bdcitnkashd4mevvcre.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ-eJRyJPHMUT0Z17V62iFAb5KengiS6k',
    appId: '1:471790702809:web:df092a0bfd6015ca20eec8',
    messagingSenderId: '471790702809',
    projectId: 'loopybot-97081',
    authDomain: 'loopybot-97081.firebaseapp.com',
    storageBucket: 'loopybot-97081.firebasestorage.app',
    measurementId: 'G-YZ84ZKNJC6',
  );
}
